import Head from 'next/head'
import Link from 'next/link';


export default function index({ data }) {
    const item = data.map(({Banner, URL, titulo, Visitas}, index) => (
        <div key={`${titulo}-${index}`}>
        <li>{titulo}</li>
        <li>{Visitas}</li>
        <li>{Banner}</li>
        </div>
    ))
    return (
        <>
            <Head>
                <title>Dashboard | Puntos colombia</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="https://landing.puntoscolombia.com/hubfs/favicon-1.png" />
            </Head>
            <div>{item}</div>
            <Link className='bg-blue-600 p-2 text-white' href='/'>Volver</Link>
        </>
    )
}

export async function getStaticPatch() {

    const respons = await fetch("https://sheetdb.io/api/v1/4p8aanmy5wtpv")
    const data = await respons.json();
    const paths = data.map(({ id }) => ({ params: { id: `${id}` } }));

    return {
        paths,
        fallback: false,
    };

}

export async function getServerSideProps({params}) {

    const respons = await fetch(`https://sheetdb.io/api/v1/4p8aanmy5wtpv/search?id=${params.id}`)
    const data = await respons.json();

    return {
        props: { data }
    }
}