import Head from 'next/head'
import Link from 'next/link';
import { ChevronDoubleLeftIcon } from '@heroicons/react/24/solid'
import Image from 'next/image';


export default function index({ data }) {

    const titulos = data.map(titulo => (
        titulo.titulo
    ))

    const item = data.map(({ Banner, URL, titulo, Visitas, tasaRebote, tiempoPagina }, index) => (
        <div key={`${titulo}-${index}`} className='flex items-center justify-center h-screen flex-col'>
            <h1 className='text-3xl py-6 text-sky-900 font-bold'>{titulo}</h1>
            <div className='flex justify-between items-center flex-row gap-[3rem] max-w-screen-lg'>
                <Image
                    alt={titulo}
                    src={Banner}
                    style={{
                        objectFit: 'fill',
                    }}
                    width={300}
                    height={500}
                />
                <div>
                    <div className='flex item-center justify-center'>
                        <div className='mx-3 flex flex-col justify-center items-center'>
                            <h2 className='text-xl text-sky-900 font-bold '>Visitas</h2>
                            <h3>{Visitas}</h3>
                        </div>
                        <div className='text-base mx-3 flex flex-col justify-center items-center'>
                            <h2 className='text-xl text-sky-900 font-bold'>Tasa de Rebote</h2>
                            <h3>{tasaRebote}</h3>
                        </div>
                        <div className='text-base mx-3 flex flex-col justify-center items-center'>
                            <h2 className='text-xl  text-sky-900 font-bold'>Tiempo en pagina</h2>
                            <h3>{tiempoPagina} Segundos</h3>
                        </div>
                    </div>
                    <div className='flex items-center justify-center py-[3rem]'>
                        <Link target="_blank" rel="noopener" href={URL} className='bg-blue-600 py-2 px-4 text-white w-fit flex flex-row rounded-lg'>
                            Ver Landing
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    ))
    return (
        <>
            <Head>
                <title>Dashboard | {titulos}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="https://landing.puntoscolombia.com/hubfs/favicon-1.png" />
            </Head>
            <div>{item}</div>
            <div className='flex items-center justify-center'>
                <Link href='/' className='bg-blue-600 py-2 px-4 text-white w-fit flex flex-row rounded-lg'>
                    <ChevronDoubleLeftIcon className="h-6 w-4 text-white" />
                    Volver
                </Link>
            </div>
        </>
    )
}

export async function getStaticPatch() {

    const respons = await fetch("https://sheetdb.io/api/v1/4p8aanmy5wtpv")
    const data = await respons.json();
    const paths = data.map(({ id }) => ({ params: { id: `${id}` } }));

    return {
        paths,
        fallback: false,
    };

}

export async function getServerSideProps({ params }) {

    const respons = await fetch(`https://sheetdb.io/api/v1/4p8aanmy5wtpv/search?id=${params.id}`)
    const data = await respons.json();

    return {
        props: { data }
    }
}