import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';




export async function getServerSideProps() {

  const respons = await fetch("https://sheetdb.io/api/v1/4p8aanmy5wtpv")
  const data = await respons.json();


  return {
    props: { data }
  }
}

export default function Home({ data }) {

  const showInfohobspot = data.map(({ Banner, titulo, Visitas, id }) => (
    <div className="flex flex-col justify-center">
      <Image
        alt={titulo}
        src={Banner}
        style={{
          objectFit: 'fill',
        }}
        width={100}
        height={200}
      />
      <Link href={`landing/${id}`}>
      <h1>{titulo}</h1>
      </Link>
      <h2>{Visitas}</h2>
    </div>
  ))

  return (
    <>
      <Head>
        <title>Dashboard | Puntos colombia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="https://landing.puntoscolombia.com/hubfs/favicon-1.png" />
      </Head>
      <div className="bg-white flex flex-justify py-24 sm:py-32">
        {showInfohobspot}
      </div>
    </>
  )
}
